### ISSUE TITLE
Depth of conv layers compared to DCGAN paper

### ISSUE THREAD

**Issue by jianglai3303** [carpedm20/DCGAN-tensorflow#101]
According to the paper, the generator reshape the noise into 4*4*1024, but in the code

self.h0 = tf.reshape(self.z_, [-1, s_h16, s_w16, self.gf_dim * 8])

// here gf_dim is 64
And the shape should be 4*4*512

Is this intentional?

**Comment by AshishBora** [comment]
Good catch! A note in the README about this difference could be helpful.

**Comment by carpedm20** [comment]
Yes that's a difference but I followed [the code](https://github.com/soumith/dcgan.torch) of Soumith who is one of the author of DCGAN. I thought if depth of layer is not that important, I preferred shorter one for a fast training.

**Comment by wkretzsch** [comment]
A note in the README would be super helpful, just like the note about training the generator twice. Also, the image in the README is a lie.  That would be helpful to have noted as well...
