### ISSUE TITLE
MNIST training seems not to work

### ISSUE THREAD

**Issue by DoctorTeeth** [carpedm20/DCGAN-tensorflow#12]
When I pass in mnist as the dataset argument, I get a failure in the definition of the generator, as y is None.
I figured that maybe I should just pass in self.y, as that exists if y_dim is not None, but this doesn't fix the problem either.

Am I missing something silly or is MNIST training just not in a working state?
Thanks for open sourcing this!

I can give more details if needed.

**Comment by carpedm20** [comment]
DCGAN with additional supervised z dimension is not implemented.
