### ISSUE TITLE
It makes my cpu very hot.

### ISSUE THREAD

**Issue by cjliux** [carpedm20/DCGAN-tensorflow#124]
I have try to run it on my computer, but....somehow it run very fast with very low cpu usage and little performance of the model while the temperature of my cpu just go up steadily and reach 80C +. It would have damaged my cpu if I had not stop it in time.....

**Comment by carpedm20** [comment]
If you are trying to train a model and you don't have a GPU, it's natural. This model is quite big and require enough computational resources to train a large number of data like celebA. However, if you're training small data like mnist, the training might be quite reasonably goes well on CPU if you are okay with hot CPU.

**Comment by cjliux** [comment]
I am not sure whether it's because of hardware compatibility.Eh...I am using tensorflow-gpu with CUDA8.0 and GTX1060.
