### ISSUE TITLE
output of generator

### ISSUE THREAD

**Issue by lanpay-lulu** [carpedm20/DCGAN-tensorflow#130]
If G is generating a picture，shouldn`t the output of G for each pixel is in range [0, 255]？
The code uses tanh or sigmoid, which can not generate such range.

How to explain that?

**Comment by carpedm20** [comment]
GAN models normalize the inputs (like [this](https://github.com/carpedm20/DCGAN-tensorflow/blob/master/utils.py#L59)) to achieve a stable learning. Maybe normalization section of http://cs231n.github.io/neural-networks-2/ and [DCGAN paper](http://arxiv.org/abs/1511.06434) itself might be helpful.
