### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by lanpay-lulu** [carpedm20/DCGAN-tensorflow#132]
I noticed that in discriminator() and generator() functions, y is concat to both input and h0 layer.
Is there any reason for doing that?
I`m new to dcgan and it confused me quite much...

**Comment by carpedm20** [comment]
If you mean by https://github.com/carpedm20/DCGAN-tensorflow/blob/master/model.py#L335 this is a form of conditional gan where generate images conditioned on y which is usually a one-hot encoded class. DCGAN has an explanation about conditional gan in appendix of its paper.
