### ISSUE TITLE
saving training images with batch_size other than 64

### ISSUE THREAD

**Issue by johnhany** [carpedm20/DCGAN-tensorflow#135]
Hi! I managed to train the networks with a custom dataset which contains over 50k samples, and the results are fantastic.

Then I tried to train another much smaller dataset with 468 images. I thought maybe it'd help to use a smaller `batch_size` rather than 64 so that I would get more iterations. I changed `mod(counter, 100) == 1` to `mod(counter, 5) == 1` because I wanted to see more intermediate results. But I got `one pic error!...` during training. Here's the script I use:

`python main.py --dataset faces --input_height 96 --output_height 48 --c_dim 3 --batch_size 20 --train_size 468 --is_train True --is_crop True --visualize True --epoch 10`

With commenting out the `try` and `except` block around line 302-311 to show the exact error messages, I trained again and got the following error:

`ValueError: Cannot feed value of shape (64, 48, 48, 3) for Tensor u'real_images: 0', which has shape '(20, 48, 48, 3)'`

It seems that even with keyword `batch_size 20` fed, somewhere in the networks somehow still assumes that `batch_size` is 64, which causes a value error.

I haven't further investigated how to resolve this issue, and hope that someone more familiar with the codes could point out for me where to look. Thanks!

**Comment by sipan17** [comment]
I have the same issue. Any ideas how to solve?

**Comment by sipan17** [comment]
I am also getting error if I specify output_height other than input_height

**Comment by johnhany** [comment]
I've located that `sample_inputs` fed into network at [here](https://github.com/carpedm20/DCGAN-tensorflow/blob/master/model.py#L306) is initialized as the size of `sample_files` which contains `self.sample_num` images. Yet `self.sample_num` is not specified when initializing object DCGAN in main.py either for mnist or other datasets.
The solution is to add `sample_num=FLAGS.batch_size` for both `dcgan` initialization. And I've already submitted a pull request for this. Hope it can be accepted.

**Comment by johnhany** [comment]
@sipan17 The current git works fine on my machine even when output_height != input_height. Can you locate the codes that caused the second issue you mentioned? Maybe it can be fixed with current version?

**Comment by sipan17** [comment]
@johnhany I checked out, but it's giving the following error
`ValueError: Trying to share variable discriminator/d_h3_lin/Matrix, but specified shape (32768, 1) and found shape (8192, 1).`

**Comment by johnhany** [comment]
@sipan17 Did you run main.py with `--is_crop=True` on? In my case, it can solve certain shape errors.

**Comment by johnhany** [comment]
Closing since this was fixed and no further related issues were raised.
