### ISSUE TITLE
CelebA download link has changed

### ISSUE THREAD

**Issue by ritsu1228** [carpedm20/DCGAN-tensorflow#14]
It looks like `CelebA` download link has changed several days ago. The original link does not work and `download.py` throws an error for `CelebA`.

Now, the correct link is: https://www.dropbox.com/sh/8oqt9vytwxb3s4r/AADIKlz8PR9zr6Y20qbkunrba/Img/img_align_celeba.zip?dl=1&pv=1

**Comment by ritsu1228** [comment]
Looks like it's already fixed.

**Comment by crizCraig** [comment]
There are new sources on http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

Google Drive:
https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8

Baidu:
http://pan.baidu.com/s/1eSNpdRG
