### ISSUE TITLE
How can i generate specific numbers of images?

### ISSUE THREAD

**Issue by georgiazhang** [carpedm20/DCGAN-tensorflow#176]
Thanks for your great work!
     Now, i can successfully run your code on my data. But i only get a merge with batch_size images.
How can i generate 10000 images, and each image is a file, not a merge.
Thank you very much!

**Comment by hellorp1990** [comment]
@georgiazhang  hi, did you solve this issue?

**Comment by rp2017** [comment]
@georgiazhang hey can you generate more than 100 images now?? did you solve it?
