### ISSUE TITLE
ValueError: Trying to share variable discriminator/d_h3_lin/Matrix, but specified shape (8192, 1) and found shape (25088, 1).

### ISSUE THREAD

**Issue by MankowitzProjects** [carpedm20/DCGAN-tensorflow#178]
Hi,

When I clone your repo, download the datasets and run the code, this is the error that I get. 
The issue comes from the assignment of variable h4 in the discriminator when calling the linear() function.

Any ideas of what the problem might be?

Thanks!

**Comment by EnJiang** [comment]
same

**Comment by CheungXu** [comment]
me too

**Comment by zhanary** [comment]
I have ever had this error, it is because I didn't type the right input command

**Comment by CheungXu** [comment]
And it seems that the size of input and output must be the same.(Parameter "input_height", "input_width' and "output_height", "output_width" ).  It works as I do so.

**Comment by MankowitzProjects** [comment]
Thanks, it was the input command in my case. I tried running it from PyCharm. In the end, I didn't set the train and crop flags in main.py to true...

**Comment by EnJiang** [comment]
For those who are viewing https://zhuanlan.zhihu.com/p/24767059 and trying to run this repo but ended up getting this error, be aware that code 
python main.py --image_size 96 --output_size 48 --dataset anime --is_crop True --is_train True --epoch 300 --input_fname_pattern "*.jpg"
in the article is wrong. Check its comments for right command.

**Comment by hscspring** [comment]
这个可以（This command works）：  
`python main.py --input_height 96 --input_width 96 --output_height 48 --output_width 48 --dataset faces --crop --train --epoch 300 --input_fname_pattern "*.jpg"`

**Comment by chunfengshiliburuni** [comment]
I got samples(training set)  those are 8*8. I want to get  some pictures which are independent each other not stitching together.
Any advice is welcome .

**Comment by awonderfullife** [comment]
Thanks a lot, it works in my computer @hscspring

**Comment by fredmax** [comment]
@MankowitzProjects and it works~thanks

**Comment by lzzlxxlsz** [comment]
And there has any size requirements when using own data?height or width?and output height or width?thanks

**Comment by tanmay00** [comment]
Does anyone got a solution or cause of this error please tell

**Comment by 989888** [comment]
Does anyone got a solution or cause of this error please tell  thank you

**Comment by TakenFromMe** [comment]
In fact,the value of input and output must be the same.

**Comment by lihh1023** [comment]
您好：       来信我已收到，我会尽快回复的。
