### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by mohanadkaleia** [carpedm20/DCGAN-tensorflow#181]
Hello,
I'm trying to train a model with a custom dataset, that consists of jpg images, I created a directory and put all images inside of it, then I run this command to train the model with: 
sudo python main.py --dataset vehicle_dataset --train --crop

But it does not train!, it start generate images from 1 - 99 and close,

**Comment by mohanadkaleia** [comment]
I found where is the problem, I had to place the dataset directory inside data directory, 
Problem solved,

**Comment by lzzlxxlsz** [comment]
Do you know the size of the input_height and width?Does the size refer to pixel size？
