### ISSUE TITLE
Wrong samples when using GPU

### ISSUE THREAD

**Issue by matheusabrantesgadelha** [carpedm20/DCGAN-tensorflow#19]
Previously, I was using the code with CPU support and everything was working fine. Now, after adding GPU support on tensorflow, the created samples are completely wrong (white noise images).

Anyone had any similar issue or an idea about what is going on?

**Comment by carpedm20** [comment]
@matheusabrantesgadelha There was a big change after 9e2117553328563e9cf347671c5ca9fcaf582e48 but I checked the latest commit works before I push it to the public. Which commit did you used and can you check whether this works with commit 9e2117553328563e9cf347671c5ca9fcaf582e48?

**Comment by matheusabrantesgadelha** [comment]
I've just figured it out. It was not an issue with the code, but with the CUDA/Tensorflow installation.

I am using a GTX 1080 and CUDA 7.5 was giving wrong results. I had to install 8.0RC, CuDNN 5 and compile tensorflow from source to make it work. Now everything is working perfectly, sorry for the trouble.
