### ISSUE TITLE
Change the dimension of z (noise)

### ISSUE THREAD

**Issue by HosnaCSE** [carpedm20/DCGAN-tensorflow#205]
Hello,
I have a question regrading random noise. I want to change the noise of z. So I change on z_dim = 4096 (it was 100 in original code). Also I change the input of batch_z. But it produces error as 

"InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [4096,32768] rhs shape= [100,32768]
         [[Node: save/Assign_38 = Assign[T=DT_FLOAT, _class=["loc:@generator/g_h0_lin/Matrix"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/g_h0_lin/Matrix, save/RestoreV2_38/_95)]]"

lhs has effect of changing dimension of z while rhs doesn't. I can't find where the error occurring or how to solve it. Any suggestion will be appreciated.

Thanks
Hosna

**Comment by asispatra** [comment]
@HosnaCSE, May be you have some saved checkpoints of previous same run. Try to run after removing or backing up the checkpoints. 

Thanks.

**Comment by HosnaCSE** [comment]
Hi @asispatra,
 Thanks it works......I appreciate your help.
