### ISSUE TITLE
np.random.uniform() generate constant array

### ISSUE THREAD

**Issue by CollinsWRQ** [carpedm20/DCGAN-tensorflow#206]
the code "np.random.uniform()" in method "sample" always generate a constant array, is it a problem or somehow it is just figured to be like this? And if there is no problem, I wanna know how to make it random. THX.

**Comment by mmbrian** [comment]
Are you sure? that can only be the case if you are sampling with the same low and high values<sup>1</sup>. If you are getting the same samples at test time then perhaps check issue [#204](../issues/204)

<sup>1</sup> https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.uniform.html
