### ISSUE TITLE
ValueError: could not broadcast input array from shape (64,64,3) into shape (64,64)

### ISSUE THREAD

**Issue by mrzl** [carpedm20/DCGAN-tensorflow#26]
Hey,

in this line: https://github.com/carpedm20/DCGAN-tensorflow/blob/master/model.py#L128 im receiving that shape error. I am training on my own data, all images scaled to the same resolution:
`data/b_dataset/scaled-1469565542658.jpg JPEG 500x500 500x500+0+0 8-bit sRGB 42.8KB 0.000u 0:00.000`

Can you give me a direction from where this might come from? I have tried with a different dataset and it works. Is there some property of the images that i have been missing in this dataset?

Thanks already,
Marcel

**Comment by genekogan** [comment]
check if the image it's failing on isn't grayscale (1-channel). that looks like that might be the problem.

**Comment by jpchen** [comment]
im having the same issue and none of my images are grayscale...
