### ISSUE TITLE
changing image_shape causes shape mismatch

### ISSUE THREAD

**Issue by genekogan** [carpedm20/DCGAN-tensorflow#27]
having trouble understanding how to change the resolution of the generated images. it appears they are hardcoded to 64. changing `image_shape` from [64, 64, 3] to [96, 96, 3] and transform/center_crop to 96, i get the error pasted below.

i know i need to change the architecture of the generator/discriminator to operate on different-sized images, but it's not as simple as switching the 64s to 96s.  is there a straightforward way to parameterize main.py so it can generate images of different resolutions?

Traceback (most recent call last):
  File "main.py", line 58, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 39, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/home/ubuntu/DCGAN-tensorflow/model.py", line 64, in __init__
    self.build_model()
  File "/home/ubuntu/DCGAN-tensorflow/model.py", line 83, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=True)
  File "/home/ubuntu/DCGAN-tensorflow/model.py", line 195, in discriminator
    h4 = linear(tf.reshape(h3, [self.batch_size, -1]), 1, 'd_h3_lin')
  File "/home/ubuntu/DCGAN-tensorflow/ops.py", line 116, in linear
    tf.random_normal_initializer(stddev=stddev))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 830, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 673, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 217, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 202, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 499, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable d_h3_lin/Matrix, but specified shape (8192, 1) and found shape (18432, 1).

**Comment by genekogan** [comment]
i figured this out by making the generator's size a function of the image's size.  this is working for me at any resolution, unsupervised or supervised.

i can submit a PR if it would be helpful.

`    
    
    def generator(self, z, y=None):
        if not self.y_dim:

            w = int(self.image_shape[0])
            w2, w4, w8, w16 = int(w/2), int(w/4), int(w/8), int(w/16)

            # project `z` and reshape
            self.z_, self.h0_w, self.h0_b = linear(z, self.gf_dim*8*w16*w16, 'g_h0_lin', with_w=True)

            self.h0 = tf.reshape(self.z_, [-1, w16, w16, self.gf_dim * 8])
            h0 = tf.nn.relu(self.g_bn0(self.h0))

            self.h1, self.h1_w, self.h1_b = deconv2d(h0, 
                [self.batch_size, w8, w8, self.gf_dim*4], name='g_h1', with_w=True)
            h1 = tf.nn.relu(self.g_bn1(self.h1))

            h2, self.h2_w, self.h2_b = deconv2d(h1,
                [self.batch_size, w4, w4, self.gf_dim*2], name='g_h2', with_w=True)
            h2 = tf.nn.relu(self.g_bn2(h2))

            h3, self.h3_w, self.h3_b = deconv2d(h2,
                [self.batch_size, w2, w2, self.gf_dim*1], name='g_h3', with_w=True)
            h3 = tf.nn.relu(self.g_bn3(h3))

            h4, self.h4_w, self.h4_b = deconv2d(h3,
                [self.batch_size, w, w, self.c_dim], name='g_h4', with_w=True)

            return tf.nn.tanh(h4)
        else:
            w = int(self.image_shape[0])
            w2, w4 = int(w/2), int(w/4) 

            # yb = tf.expand_dims(tf.expand_dims(y, 1),2)
            yb = tf.reshape(y, [self.batch_size, 1, 1, self.y_dim])
            z = tf.concat(1, [z, y])

            h0 = tf.nn.relu(self.g_bn0(linear(z, self.gfc_dim, 'g_h0_lin')))
            h0 = tf.concat(1, [h0, y])

            h1 = tf.nn.relu(self.g_bn1(linear(z, self.gf_dim*2*w4*w4, 'g_h1_lin')))            
            h1 = tf.reshape(h1, [self.batch_size, w4, w4, self.gf_dim * 2])

            h1 = conv_cond_concat(h1, yb)

            h2 = tf.nn.relu(self.g_bn2(deconv2d(h1, [self.batch_size, w2, w2, self.gf_dim * 2], name='g_h2')))
            h2 = conv_cond_concat(h2, yb)

            return tf.nn.sigmoid(deconv2d(h2, [self.batch_size, w, w, self.c_dim], name='g_h3'))

    def sampler(self, z, y=None):
        tf.get_variable_scope().reuse_variables()

        if not self.y_dim:

            w = int(self.image_shape[0])
            w2, w4, w8, w16 = int(w/2), int(w/4), int(w/8), int(w/16)
            
            # project `z` and reshape
            h0 = tf.reshape(linear(z, self.gf_dim*8*w16*w16, 'g_h0_lin'),
                            [-1, w16, w16, self.gf_dim * 8])
            h0 = tf.nn.relu(self.g_bn0(h0, train=False))

            h1 = deconv2d(h0, [self.batch_size, w8, w8, self.gf_dim*4], name='g_h1')
            h1 = tf.nn.relu(self.g_bn1(h1, train=False))

            h2 = deconv2d(h1, [self.batch_size, w4, w4, self.gf_dim*2], name='g_h2')
            h2 = tf.nn.relu(self.g_bn2(h2, train=False))

            h3 = deconv2d(h2, [self.batch_size, w2, w2, self.gf_dim*1], name='g_h3')
            h3 = tf.nn.relu(self.g_bn3(h3, train=False))

            h4 = deconv2d(h3, [self.batch_size, w, w, self.c_dim], name='g_h4')

            return tf.nn.tanh(h4)
        else:
            w = self.image_shape[0]
            w2, w4 = int(w/2), int(w/4)

            #yb = tf.reshape(y, [-1, 1, 1, self.y_dim])
            yb = tf.reshape(y, [self.batch_size, 1, 1, self.y_dim])

            z = tf.concat(1, [z, y])

            h0 = tf.nn.relu(self.g_bn0(linear(z, self.gfc_dim, 'g_h0_lin')))
            h0 = tf.concat(1, [h0, y])

            h1 = tf.nn.relu(self.g_bn1(linear(z, self.gf_dim*2*w4*w4, 'g_h1_lin'), train=False))
            h1 = tf.reshape(h1, [self.batch_size, w4, w4, self.gf_dim * 2])
            h1 = conv_cond_concat(h1, yb)

            h2 = tf.nn.relu(self.g_bn2(deconv2d(h1, [self.batch_size, w2, w2, self.gf_dim * 2], name='g_h2'), train=False))
            h2 = conv_cond_concat(h2, yb)

            return tf.nn.sigmoid(deconv2d(h2, [self.batch_size, w, w, self.c_dim], name='g_h3'))
`

**Comment by carpedm20** [comment]
@genekogan Yes, please. It would be helpful! Thanks.

**Comment by genekogan** [comment]
PR submitted [here](https://github.com/carpedm20/DCGAN-tensorflow/pull/30). let me know if it works.
thanks for this codebase!!
