### ISSUE TITLE
lrelu complexity?

### ISSUE THREAD

**Issue by alexmonroe87** [carpedm20/DCGAN-tensorflow#28]
Why did you implement lrelu the way you did?

Would this not be more efficient?

`tf.maximum(x, leak*x)`

**Comment by carpedm20** [comment]
@alexmonroe87 Thanks! I fix the code.

**Comment by kbrose** [comment]
I think that's wrong...? Did anyone do any speed/memory benchmarks?

https://github.com/tensorflow/tensorflow/issues/4079
