### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 1451595897** [carpedm20/DCGAN-tensorflow#285]
When I run the model,it shows the error that "IndexError: list index out of range".

![1](https://user-images.githubusercontent.com/39090271/39759773-1fb0f3f8-5306-11e8-865b-fa23c3742bb6.png)

**Comment by Laxse** [comment]
Does it fixed now?

**Comment by Laxse** [comment]
IndexError: list index out of range with custom dataset #254
please see that⬆️

**Comment by jdenneytwitter** [comment]
@1451595897 I got this error due to it not finding my images files because I did not set a "--input_fname_pattern".  I think it defaults to '*.jpg'.   I plan on submitting a PR to make it return a more informative error.

**Comment by spacemunkay** [comment]
I got this error due to it not finding my images files because I did not set a "--input_fname_pattern". I think it defaults to '*.jpg'. I plan on submitting a PR to make it return a more informative error.
