### ISSUE TITLE
extract feature vector from existing image

### ISSUE THREAD

**Issue by shaih82** [carpedm20/DCGAN-tensorflow#3]
hey, can i use DCGAN to extract feature vector of an existing image?

**Comment by carpedm20** [comment]
Yes it's possible by using the last or higher layer of D network but don't know how it is representative than features vector of other discriminative models like VGG.

**Comment by 0buo** [comment]
Is there a way to save / freeze discriminator network? In the frezon graph it seems there is only the generator.
