### ISSUE TITLE
How to load a checkponit?

### ISSUE THREAD

**Issue by RuikangSun** [carpedm20/DCGAN-tensorflow#345]
When I load main.py, it will tell me “Failed to find a checkpoint“ ”Load failed”
and then start training from the beginning.

**Comment by RuikangSun** [comment]
It works!
Video: https://www.bilibili.com/video/av56967234

**Comment by RuikangSun** [comment]
![train_00024400](https://user-images.githubusercontent.com/20597187/60263490-5fab4900-9913-11e9-8f9d-7e987c5dfb0a.png)

**Comment by simonharrisco** [comment]
Hi. What did you have to change? I also keep getting 'failed to load checkpoint'

**Comment by michaelyan-coupa** [comment]
I am also getting this error

**Comment by avaseghi** [comment]
Can you please post your solution?

**Comment by maz369** [comment]
I have a similar issue. Someone suggested to hardcode directory of the check point in the main.py as shown in the following.  This way it will find the checkpoint but raises another error saying **TypeError: 'NoneType' object is not iterable**. I am getting this error even when training CelebA. Please let me know if you know how to solve this or any suggestion.


if FLAGS.train:
      dcgan.train(FLAGS)
    else:
        #load_success, load_counter = dcgan.load(FLAGS.checkpoint_dir)
        load_success, load_counter = dcgan.load('/ifs/loni/faculty/shi/spectrum/Maz/DL/DCGAN/out/20191105.164122 - data - oct_mask - x28.z100.uniform_signed.y64.b64/checkpoint')

**Comment by RuikangSun** [comment]
Close old issues.
