### ISSUE TITLE
HI, I have a problem with learning my own data

### ISSUE THREAD

**Issue by MPLAP** [carpedm20/DCGAN-tensorflow#348]
My image figure resize 64*64*24b and 178*128*24b, I got the following error

Exception : [!] Entire dataset size is less than the configured batch_size

The command was entered as:
python main.py --dataset DATASET_NAME --train
python main.py --dataset=DATASET_NAME --input_fname_pattern="*.jpg" --train

How can i solve this problem?

**Comment by KOPFC** [comment]
Change the `batch_size` to a number that smaller than the total number of your data set.

**Comment by MPLAP** [comment]
Thank you for your help! :D
But there was an error elsewhere.
I put 75 input data, I entered the following command.
 
python main.py --input_height 256 --input_width 256 --output_height 64 --output_width 64 --dataset Foldername --crop --train --epoch 300 --input_fname_pattern "*.jpg"
 
The error message is as follows.
​[*] Reading checkpoints... ./out\20190715.213847 - data - Foldername - x256.z100.uniform_signed.y64.b64\checkpoint
[*] Failed to find a checkpoint
[!] Load failed...

Can you help me with this??
Thank you for your help :D!

​

**Comment by sachitha-bandara** [comment]
Hi @MPLAP can you tell me how you solved the problem?
