### ISSUE TITLE
celebA dataset is not accessible

### ISSUE THREAD

**Issue by IchibanKanobee** [carpedm20/DCGAN-tensorflow#38]
I've been trying to download celebA dataset for a couple of weeks now
"python download.py celebA",
but it always generates the same error:
urllib2.HTTPError: HTTP Error 429: Too Many Requests

**Comment by prichey** [comment]
+1

**Comment by madaiqian** [comment]
+1

**Comment by carpedm20** [comment]
Currently celebA (http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) data can't be downloaded because of the dropbox download policy as https://www.dropbox.com/sh/8oqt9vytwxb3s4r/AAB06FXaQRUNtjW9ntaoPGvCa?dl=0. There is no way to download celebA if there are no other links for the data.

**Comment by SchafferZhang** [comment]
I have downloaded it from other source,but which path should I put the file to?

**Comment by stoneyang** [comment]
@SchafferZhang put em under data directory. Note that the directory name should be `celebA` and only contains jpg files.

**Comment by crizCraig** [comment]
There are new sources on http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

Google Drive:
https://drive.google.com/open?id=0B7EVK8r0v71pWEZsZE9oNnFzTm8

Baidu:
http://pan.baidu.com/s/1eSNpdRG

**Comment by elinx** [comment]
The dataset has been upload to kaggle, it's faster to download to me. https://www.kaggle.com/jessicali9530/celeba-dataset
