### ISSUE TITLE
what to expect when we train?

### ISSUE THREAD

**Issue by evanthebouncy** [carpedm20/DCGAN-tensorflow#39]
I'm just doing the training on mnist and bunch of stuff that looks like this scroll past

```
Epoch: [ 1] [ 775/1093] time: 155.6176, d_loss: 1.39283180, g_loss: 0.67132330
```

how long should I wait? Is the model being saved periodically or does the script ends in a set amount say... 20 epochs and then we can do the testing part? So far I'm just not sure what to expect, should I leave it running for a day? Does it automatically save the ckpt models? Should I ctrl-C out in an hour?

It terminated by itself after awhile.

```
Epoch: [24] [1092/1093] time: 2298.4984, d_loss: 1.39633536, g_loss: 0.64348722
```

I'm not sure what to do now actually. I tried to do the test script and nothing happens...

```
/DCGAN-tensorflow$ python main.py --dataset mnist
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
{'batch_size': 64,
 'beta1': 0.5,
 'c_dim': 3,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'mnist',
 'epoch': 25,
 'image_size': 108,
 'is_crop': False,
 'is_train': False,
 'learning_rate': 0.0002,
 'output_size': 64,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 980M
major: 5 minor: 2 memoryClockRate (GHz) 1.1265
pciBusID 0000:01:00.0
Total memory: 8.00GiB
Free memory: 7.64GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0)
 [*] Reading checkpoints...
```

It just stops and nothing happens. What should I expect?
thanks!

**Comment by immexerxez** [comment]
any news on this issue? Fantastic library so far, @carpedm20 keep up the great work!

**Comment by carpedm20** [comment]
While you are training, samples are generated by trained generator and the images are saved in `samples` directory which can be changed by https://github.com/carpedm20/DCGAN-tensorflow/blob/master/main.py#L21. You can see how it is trained by looking at the images that are generated

**Comment by immexerxez** [comment]
@carpedm20 sorry to be a bother if you are busy, I`m not very familiar with this NN architecture, just came across the paper about DCGAN`s last week. Do you think this could be a viable solution for unsupervised image classification?

**Comment by kursatozdalli** [comment]
After testing there are no images under "samples" directory.
Thanks

**Comment by carpedm20** [comment]
@kursatozdalli You can now see the samples with `visualize` function in https://github.com/carpedm20/DCGAN-tensorflow/blob/master/utils.py#L146. Please pull and try again.
