### ISSUE TITLE
Probable error in model.py lines 84 and 87

### ISSUE THREAD

**Issue by biswajitsc** [carpedm20/DCGAN-tensorflow#42]
Shouldn't the order of "self.D_logits, self.D" and  "self.D_logits_, self.D_" be reversed? Since discriminator returns in the order (prob, logit)

**Comment by carpedm20** [comment]
Yes, this is weird. Thanks for finding this!

@PhoenixDai Hi, I think you changed the order while fixing c8925bc21983f25acddc9ad39291e55f996520de. Is there any reason why?

**Comment by PhoenixDai** [comment]
I'm investigating it. As far as I can recall, I believe I do have a reason but it might also be a typo. I will update you about my findings. Sorry for not documenting it.

**Comment by carpedm20** [comment]
Fixed with #49
