### ISSUE TITLE
Intermediate Layer is Ignored

### ISSUE THREAD

**Issue by nroth1** [carpedm20/DCGAN-tensorflow#44]
In lines 344-345 of model.py, we calculate h0 as follows:

`h0 = tf.nn.relu(self.g_bn0(linear(z, self.gfc_dim, 'g_h0_lin')))`
`h0 = tf.concat(1, [h0, y])`

But this output, h0 is not used anywhere in the generator, as far as I can tell. 

It seems like in the proceeding line:

`h1 = tf.nn.relu(self.g_bn1(linear(z, self.gf_dim*2*s4*s4, 'g_h1_lin'), train=False))`

We ought to replace z with h0? Am I missing something?

**Comment by carpedm20** [comment]
Thanks! This is same issue with #45 and I'll fix this.

**Comment by carpedm20** [comment]
Fixed. #48
