### ISSUE TITLE
Possible issue between line 300 to 320, for generator based on y

### ISSUE THREAD

**Issue by zchen0211** [carpedm20/DCGAN-tensorflow#45]
h0 = tf.nn.relu(self.g_bn0(linear(z, self.gfc_dim, 'g_h0_lin')))
h0 = tf.concat(1, [h0, y])

h1 = tf.nn.relu(self.g_bn1(linear(z, self.gf_dim*2*s4*s4, 'g_h1_lin')))            
h1 = tf.reshape(h1, [self.batch_size, s4, s4, self.gf_dim * 2])

h1 directly uses linear of z rather than h0. I guess this is a bug? :) Also same thing for following layers.

**Comment by carpedm20** [comment]
Thanks. Yes this seems to be an error but it still works because generator and discriminator has same network. This is same issue with #44 and I'll fix this.

**Comment by immexerxez** [comment]
treid out the change , seems to produce better results faster.

**Comment by carpedm20** [comment]
@immexerxez You mean you tested on MNIST data? You can give me an pull request if you don't mind.

**Comment by immexerxez** [comment]
Yes on mnist, absolutely

**Comment by carpedm20** [comment]
Fixed. #48
