### ISSUE TITLE
how to get Asian face dataset?

### ISSUE THREAD

**Issue by zhangqianhui** [carpedm20/DCGAN-tensorflow#46]
the README introduce the trained result of asian face dataset ?
How do i get this dataset?

**Comment by carpedm20** [comment]
You need to crawl by yourself. There is no public dataset for asian face.

**Comment by fresh2tensorflow** [comment]
i am looking for it too.

**Comment by viethungtsdv** [comment]
hi @zhangqianhui , @fresh2tensorflow 
you can get the asian face datasets with name: Asian-Celeb 93,979 ids with 2,830,146 aligned images
at: https://github.com/deepinsight/insightface/issues/256

Good luck.
