### ISSUE TITLE
Generating Photo-realistic Avatars with DCGAN

### ISSUE THREAD

**Issue by kaihuchen** [carpedm20/DCGAN-tensorflow#56]
@carpedm20  I want to thank you for making your code available. I know you said that your code is kind of old, but nonetheless I got a lot of mileage out of it and was able to do some interesting research about using DCGAN to create photo-realistic avatars from small amount of images or videos.

Here are some quick results showing synthesized Adele expression out of a small video segment.

A smile ![A smile](http://www.terraai.org/content/images/2016/11/look-up-and-smile-1.gif) 
A growl ![Adele growls](http://www.terraai.org/content/images/2016/11/growl.gif)

My full report can be found here: http://www.terraai.org/avatars/

**Comment by carpedm20** [comment]
Thanks for sharing the results. Now I close this issue.
