### ISSUE TITLE
SpatialFullConvolution is Fully Connected Layer + Reshape Layer ?

### ISSUE THREAD

**Issue by zsdonghao** [carpedm20/DCGAN-tensorflow#58]
Hi I wonder why `SpatialFullConvolution`(torch) is dense layer + reshape layer, as I know `SpatialFullConvolution` is deconvolutional layer.

It is a mistake in your code?

torch ref: https://github.com/soumith/dcgan.torch/blob/master/main.lua

**Comment by ppwwyyxx** [comment]
SpatialFullConvolution on 1x1 input is equivalent to a dense layer.

**Comment by zsdonghao** [comment]
@ppwwyyxx thank you very much.
