### ISSUE TITLE
spatial_conv function is not defined anywhere in the project.

### ISSUE THREAD

**Issue by leconteur** [carpedm20/DCGAN-tensorflow#6]
It is used in the line 176 of the model.py file.

**Comment by carpedm20** [comment]
@leconteur The DCGAN model with z + external y is not implemented in this project. But it should be changed from `spatial_conv` to `conv2d`

**Comment by leconteur** [comment]
Ok. I will implement this in my own fork. Thank you.

Nice project by the way.
