### ISSUE TITLE
ValueError: Variable d_h0_conv/w/Adam/ does not exist

### ISSUE THREAD

**Issue by zhangqianhui** [carpedm20/DCGAN-tensorflow#66]
when running on mnist dataset, I got this error.
`
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`
Can you help me to explain it?

Thanks

**Comment by carpedm20** [comment]
@zhangqianhui The issue is solved. Please try again.

**Comment by chihyaoma** [comment]
@carpedm20 Can you please elaborate a little bit about what exactly is the problem? I can see that the main changes are basically using `tf.variable_scope()` for discriminator and generator. 

```python
with tf.variable_scope("discriminator") as scope:
    scope.reuse_variables()

with tf.variable_scope("generator") as scope: 
    scope.reuse_variables()
```

I faced the same issue in using [improved-gan](https://github.com/openai/improved-gan/tree/master/imagenet), but as a beginner for TensorFlow, I found out that it's not as straightforward as I thought. I am still trying to figure out how to solve it in the improved-gan repository. Any additional information will be a huge help to me!

**Comment by zhangqianhui** [comment]
@carpedm20  thanks

**Comment by FlyingTourist** [comment]
@chihyaoma To resolve the issue on improved-gan, I found [this](https://github.com/tensorflow/tensorflow/issues/6220) to work

**Comment by awonderfullife** [comment]
Thanks for your sharing~@FlyingTourist, it helps a lot
