### ISSUE TITLE
AttributeError: 'module' object has no attribute 'summary'

### ISSUE THREAD

**Issue by clkruse** [carpedm20/DCGAN-tensorflow#67]
I have to believe that this is user error, but I've been bashing my head against it for a bit now. When I try to run the mnist toy example, I get `AttributeError: 'module' object has no attribute 'summary'`

Running on python 2.7.10 and TensorFlow 0.12.0rc1

Full text below:
`python main.py --dataset mnist --is_train True
{'batch_size': 64,
 'beta1': 0.5,
 'c_dim': 3,
 'checkpoint_dir': 'checkpoint',
 'dataset': 'mnist',
 'epoch': 25,
 'image_size': 108,
 'is_crop': False,
 'is_train': True,
 'learning_rate': 0.0002,
 'output_size': 64,
 'sample_dir': 'samples',
 'train_size': inf,
 'visualize': False}
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "main.py", line 38, in main
    dataset_name=FLAGS.dataset, is_crop=FLAGS.is_crop, checkpoint_dir=FLAGS.checkpoint_dir, sample_dir=FLAGS.sample_dir)
  File "/Users/ckruse/Documents/Python/DCGAN-tensorflow-master/model.py", line 67, in __init__
    self.build_model()
  File "/Users/ckruse/Documents/Python/DCGAN-tensorflow-master/model.py", line 80, in build_model
    self.z_sum = tf.summary.histogram("z", self.z)`

**Comment by carpedm20** [comment]
If you are truly using `0.12.0`, you should not see this error as below.

    In [2]: tf.__version__
    Out[2]: '0.12.head'

    In [3]: tf.summary.histogram
    Out[3]: <function tensorflow.python.summary.summary.histogram>

**Comment by clkruse** [comment]
Somehow I had two versions of TensorFlow installed, and I was calling the older version. All is solved.
