### ISSUE TITLE
issue in training

### ISSUE THREAD

**Issue by Exception4U** [carpedm20/DCGAN-tensorflow#71]
File "main.py", line 44, in main
    dcgan.train(FLAGS)
  File "/home/tushar/codes/python_codes/DCGAN-tensorflow/model.py", line 131, in train
    init_op = tf.global_variables_initializer()
AttributeError: 'module' object has no attribute 'global_variables_initializer'

**Comment by MustafaMustafa** [comment]
You are using an older version an older version of TF. I added a try/except block to address backward compatibility #72 . @carpedm20 will merge it when he wakes up.

**Comment by carpedm20** [comment]
I think this issue is solved.
