### ISSUE TITLE
Depth of conv layers compared to DCGAN paper

### ISSUE THREAD

**Issue by MustafaMustafa** [carpedm20/DCGAN-tensorflow#74]
Hi Taehoon, 

Just to be sure, the number of filters in your implementation is half of those in the original paper. For example, with default gf_dim=64 the first layer of the generator has 512 instead of 1024 as in the original paper. 

Is this intentional?

**Comment by jiang2764** [comment]
I also found this. The dimension of first layer - fully connected layer for generator is 4x4x512 instead of 4x4x1024 as described in the paper. Are there any special reason? Thanks. @MustafaMustafa @carpedm20
