### ISSUE TITLE
What's mean of "y_dim"

### ISSUE THREAD

**Issue by FormatFish** [carpedm20/DCGAN-tensorflow#75]
Hi ,
I just read the paper and your code , and I find "y_dim" in your model.py function of generator , Is that the label for vector z?
and just like "LAPGAN" , the y_dim is just like conditioning variable which aim is to control the generator model?

**Comment by mikigom** [comment]
You can see that both ```generator``` and ```discriminator``` model include ```y``` term if dataset is ```mnist```. I think ```y_dim``` means number of dimension of label of each data (I mean, if dataset is ```mnist```, it means 10. e.g. 0, 1, 2, ... 9.) and this model architecture is closer to cGAN rather than LAPGAN.

**Comment by carpedm20** [comment]
Yes it's a conditional variable which is described in appendix of [the paper](http://arxiv.org/abs/1511.06434) which makes DCGAN as a conditional generative model.

**Comment by ttdbb1** [comment]
so
