### ISSUE TITLE
sigmoid_cross_entropy_with_logits does not have `labels` arg

### ISSUE THREAD

**Issue by jscottcronin** [carpedm20/DCGAN-tensorflow#84]
Hello,

I'm having some difficulties getting the example code to execute. I believe the issue stems from a tensorflow versioning delta. I first tried to train a model on the celebA data after setting up a cpu tensorflow docker container from: https://hub.docker.com/r/tensorflow/tensorflow/

When I run
```
python main.py --dataset celebA --input_height=108 --is_train --is_crop True
```
I get the following traceback:
```
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 76, in main
    sample_dir=FLAGS.sample_dir)
  File "/root/git_repos/DCGAN-tensorflow/model.py", line 71, in __init__
    self.build_model()
  File "/root/git_repos/DCGAN-tensorflow/model.py", line 115, in build_model
    logits=self.D_logits, labels=tf.ones_like(self.D)))
TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'
```

After looking, I found sigmoid_cross_entropy_with_logits here: https://github.com/tensorflow/tensorflow/blob/cb17d1b0e2b581b5da1d9597b7929ba764749d38/tensorflow/python/ops/nn_impl.py#L99
which shows that it does take a `labels` arg. However, the version under v0.12.1 does not take this arg which I believe is the error I'm receiving above.

Furthermore, if I try to install the specific version of tensorflow branch that you linked to:
```
pip install git+https://github.com/tensorflow/tensorflow.git@r0.12
```
I get the following traceback:
```
Collecting git+https://github.com/tensorflow/tensorflow.git@r0.12
  Cloning https://github.com/tensorflow/tensorflow.git (to r0.12) to /tmp/pip-oKC0L1-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-oKC0L1-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-oKC0L1-build/
```

Any suggestions on how to get this up and running?

Thanks,
Scott

**Comment by ppwwyyxx** [comment]
Yes the argument only exist in new version of TensorFlow.

Your command is not the right way to install TensorFlow. Please refer to the documentation: https://github.com/tensorflow/tensorflow#installation .
(For this new feature you may need the nightly build)

**Comment by jscottcronin** [comment]
Thanks for the suggestion. The code executed once I installed the nightly build.

**Comment by fanshi118** [comment]
Same issue here. How do we install nightly build? I tried to download the wheel file to my local directory, but the installation didn't happen smoothly. Is it possible for you guys to provide more instruction on that?

Thanks,
Shi

**Comment by carpedm20** [comment]
You can use any links in https://github.com/tensorflow/tensorflow#installation like:

    pip install -U https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.0.0rc1-cp27-none-linux_x86_64.whl

**Comment by datatales2017** [comment]
Can you gime me the link for the nightly code for windows??

**Comment by himanshurobo** [comment]
Worked for me
`pip install -U  tensorflow`

**Comment by rezwanulhaquerezwan** [comment]
Recently I am working with ANN and  facing issues while performing ANN .

```python
In [6]: classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
__main__:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
```
--------
```python
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
__main__:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
```

```python
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
__main__:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
```
and Finally , When I am trying to compile the ANN, I am getting following error.

```python
In [9]: classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
Traceback (most recent call last):

  File "<ipython-input-9-bdfe6dd46c1c>", line 1, in <module>
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/keras/models.py", line 784, in compile
    **kwargs)

  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/keras/engine/training.py", line 850, in compile
    sample_weight, mask)

  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/keras/engine/training.py", line 450, in weighted
    score_array = fn(y_true, y_pred)

  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/keras/losses.py", line 57, in binary_crossentropy
    return K.mean(K.binary_crossentropy(y_true, y_pred), axis=-1)

  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2822, in binary_crossentropy
    logits=output)

TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'
```

# N.B: spyder, mac os

How can I solve this error ?

**Comment by datatales2017** [comment]
I think you are not working on the latest version of tensor flow. Update
the version.

**Comment by sushilshah** [comment]
@rezwanulhaquerezwan I am getting the exact same error, did you managed to fix it? How to fix it?

**Comment by sushilshah** [comment]
`pip install -U tensorflow ` fixed the issue for me

**Comment by ncyaodi** [comment]
Hi,
I am compile my model: 
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']),

And got the same error:
TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'

Tried to update my tensorflow to 1.4.0. Tried sushilshah's method. Neither works.

Can anyone help?

**Comment by palashhedau** [comment]
Did you tried restarting your tensorflow and IDE after reinstalling  with command pip install -U tensorflow ?
Worked for me

**Comment by ncyaodi** [comment]
thanks, I did try. And it worked for me.

Sorry for not coming back to close it.
