### ISSUE TITLE
The code cannot use with tf12.1

### ISSUE THREAD

**Issue by jinsiyu** [carpedm20/DCGAN-tensorflow#88]
The API histogram_summary and image_summary were deleted in r12.1. Maybe I shall roll back to 11.0

**Comment by carpedm20** [comment]
That's why I add `try catch` code like https://github.com/carpedm20/DCGAN-tensorflow/blob/9879482aadf021e5bef923c361c7b7d2a6fa8bc5/ops.py#L9. Is there any problem yet?

**Comment by jinsiyu** [comment]
Solved. Thanks!
