### ISSUE TITLE
TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by iFighting** [carpedm20/DCGAN-tensorflow#90]
i run the code, and i have this error,do you know why?
logits=self.D_logits, labels=tf.ones_like(self.D)))
TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'

**Comment by carpedm20** [comment]
You should update your TensorFlow version

**Comment by iFighting** [comment]
my TensorFlow version is the latest, i have modify the code by replacing the  labels with targets.
it runs well

**Comment by carpedm20** [comment]
Actually, you're not. You may use 'pip install -U' but it's not installing the lastest. See #89.

**Comment by linrio** [comment]
Changing `labels` to `targets` , And I fixed this problem.
