### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by fengwei2014** [carpedm20/DCGAN-tensorflow#99]
run code :
```shell
python main.py --dataset mnist --input_height=28 --output_height=28 --c_dim=1 --is_train 
```
![image](https://cloud.githubusercontent.com/assets/7076918/22734382/71b090b4-ee30-11e6-911e-62d01bccbaff.png)

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by mrjel** [comment]
Hello,

In model.py line 388 is written the following:
`z = tf.concat([z, y], 1)`
It needs to be changed to
`z = concat([z, y], 1)`
in order to use the custom concat function which choses the correct parameter layout.

Regards,
Jan

**Comment by carpedm20** [comment]
@mrjel Thanks!

**Comment by fengwei2014** [comment]
Update to the latest code, But TypeError is still here ... @carpedm20

**Comment by tangyudi** [comment]
@mrjel @carpedm20 There still exist the error like@fengwei2014  TypeError: Expected int32, got list containing Tensors of type '_Message' instead.?  How to solve the error? Thank you!

**Comment by ppwwyyxx** [comment]
@tangyudi Update tensorflow would probably solve your problem.

**Comment by zhaotiny** [comment]
Ｉalso get the same error

**Comment by pandamax** [comment]
same error encounted

**Comment by BerenLuthien** [comment]
Same error encountered. Tensorflow 1.0.0

**Comment by BerenLuthien** [comment]
Mine was stupid .... I simply did not notice... FYI : 
Instead of using 
`HyperColumns = tf.concat(0 , [layer1, layer2], )`

I should use 
`HyperColumns = tf.concat([layer1, layer2], 0)`

**Comment by woshidaerduotu99** [comment]
@fengwei2014 have you solved this problem?Can you tell me this method?

**Comment by tcglarry** [comment]
I also met the issues, 
my solution: change tf.concat to tf.concat_v2

That's all...and it works.!

**Comment by midnitekoder** [comment]
@tcglarry it worked for me as well but I don't understand why...
